# LLM模型配置
models:
  default:
    provider: "openai"
    model: "gpt-4"
    temperature: 0.7
    max_tokens: 500
    timeout: 30

  fallback:
    provider: "anthropic"
    model: "claude-2"
    temperature: 0.7
    max_tokens: 500
    timeout: 30

# 记忆管理
memory:
  short_term:
    max_rounds: 10  # 保存最近10轮的对话
    max_tokens: 2000  # 短期记忆的最大token数

  long_term:
    database: "chromadb"
    collection: "poker_memories"
    similarity_threshold: 0.85
    max_results: 5  # 检索时返回的最大结果数

# 决策参数
decision:
  confidence_threshold: 0.7  # 最小决策置信度
  max_retries: 3  # 决策失败时的最大重试次数
  fallback_strategy: "fold"  # 决策失败时的默认策略

# 玩家个性
personalities:
  - name: "激进型"
    description: "倾向于加注和诈唬的激进玩家"
    aggression_factor: 0.8
    bluff_frequency: 0.3

  - name: "保守型"
    description: "倾向于稳健打法的保守玩家"
    aggression_factor: 0.3
    bluff_frequency: 0.1

  - name: "平衡型"
    description: "在激进和保守之间保持平衡的玩家"
    aggression_factor: 0.5
    bluff_frequency: 0.2

# 提示词模板
prompts:
  decision_making: |
    你是一个德州扑克玩家，当前情况如下：
    底牌：{hand_cards}
    公共牌：{community_cards}
    当前行动：{current_action}
    底池：{pot_size}
    位置：{position}
    其他玩家行为：{player_actions}
    历史经验：{historical_context}
    
    请基于以上信息做出决策，输出格式为JSON：
    {
      "action": {
        "type": "CALL|RAISE|FOLD|CHECK",
        "amount": 数值,
        "confidence": 0.0-1.0
      },
      "reasoning": {
        "hand_strength": "强牌/中等/弱牌",
        "position_analysis": "位置优势/劣势分析",
        "pot_odds": "底池赔率分析",
        "opponent_reads": ["玩家行为分析"],
        "historical_context": ["相关历史经验"]
      },
      "table_talk": {
        "message": "发言内容",
        "tone": "友好/紧张/自信"
      }
    }
